In [7]:
import numpy as np
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.optim as optim
import torch.nn.functional as F
import torch.utils.data
import torchvision
from torchvision import datasets, models, transforms

In [4]:
x = torch.Tensor(5,3)
y = torch.rand(5,3)
z = x + y

In [5]:
print(x,y,z)


 0.0000e+00  0.0000e+00  6.4942e-29
-3.6893e+19  1.0304e-32  1.4013e-45
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
 0.0000e+00  0.0000e+00  0.0000e+00
[torch.FloatTensor of size 5x3]
 
 0.4498  0.6943  0.5695
 0.1888  0.8955  0.8295
 0.8212  0.7534  0.7892
 0.3707  0.7719  0.5811
 0.9851  0.2825  0.0009
[torch.FloatTensor of size 5x3]
 
 4.4977e-01  6.9430e-01  5.6950e-01
-3.6893e+19  8.9548e-01  8.2951e-01
 8.2120e-01  7.5341e-01  7.8919e-01
 3.7072e-01  7.7194e-01  5.8111e-01
 9.8510e-01  2.8248e-01  9.4360e-04
[torch.FloatTensor of size 5x3]



In [8]:
x = np.random.rand(5,3)
y = torch.from_numpy(x)
z = y.numpy()

In [9]:
print(x,y,z)

[[ 0.92280904  0.63570376  0.60768095]
 [ 0.24550455  0.19420691  0.46887658]
 [ 0.38943848  0.68533005  0.76513561]
 [ 0.77169522  0.91112476  0.21907667]
 [ 0.57183986  0.45291866  0.00451958]] 
 0.9228  0.6357  0.6077
 0.2455  0.1942  0.4689
 0.3894  0.6853  0.7651
 0.7717  0.9111  0.2191
 0.5718  0.4529  0.0045
[torch.DoubleTensor of size 5x3]
 [[ 0.92280904  0.63570376  0.60768095]
 [ 0.24550455  0.19420691  0.46887658]
 [ 0.38943848  0.68533005  0.76513561]
 [ 0.77169522  0.91112476  0.21907667]
 [ 0.57183986  0.45291866  0.00451958]]


In [10]:
x = torch.rand(5,3)
y = Variable(x)
z = torch.pow(y, 2) + 2

In [11]:
print(x,y,z)


 0.0726  0.2804  0.3156
 0.2981  0.0386  0.7100
 0.1632  0.8164  0.6523
 0.7157  0.1771  0.0690
 0.2580  0.5217  0.4434
[torch.FloatTensor of size 5x3]
 Variable containing:
 0.0726  0.2804  0.3156
 0.2981  0.0386  0.7100
 0.1632  0.8164  0.6523
 0.7157  0.1771  0.0690
 0.2580  0.5217  0.4434
[torch.FloatTensor of size 5x3]
 Variable containing:
 2.0053  2.0786  2.0996
 2.0888  2.0015  2.5041
 2.0266  2.6666  2.4255
 2.5123  2.0314  2.0048
 2.0666  2.2722  2.1966
[torch.FloatTensor of size 5x3]



## Numpy version

In [14]:
# N is batch size, D is input and output dimension, H is hidden dimension
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random input and output data
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

lr = 1e-6
epoch = 500
for t in range(epoch):
    # Forward pass: compute predicted y
    h = x.dot(w1)
    h_relu = np.maximum(h, 0)
    y_pred = h_relu.dot(w2)
    
    # Compute and print loss
    loss = np.square(y_pred - y).sum()
    print(t, loss)
    
    # Backprop to compute gradients of w1 and w2 with respect to loss
    # grad_y_pred is gradient of y_pred
    grad_y_pred = 2.0 * (y_pred - y)
    # grad_w2 is gradient of w2
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)
    
    # Update weights
    w1 -= lr * grad_w1
    w2 -= lr * grad_w2

0 32867380.2942
1 29146392.7792
2 28390987.2837
3 26193104.6984
4 21030691.9657
5 14443982.5315
6 8764182.01849
7 5051378.99254
8 2982084.21399
9 1898505.64666
10 1323078.58262
11 997102.869045
12 795000.939663
13 657474.970114
14 556216.84397
15 477422.851485
16 413861.987848
17 361298.284159
18 317220.248103
19 279776.301454
20 247735.295803
21 220127.500681
22 196253.001138
23 175456.671392
24 157268.55484
25 141325.358055
26 127292.374455
27 114937.056214
28 104007.36126
29 94296.1538476
30 85644.6724215
31 77922.5795415
32 71016.9356833
33 64826.7148978
34 59267.2822533
35 54258.4100938
36 49737.6865146
37 45652.6797945
38 41954.1606801
39 38604.6740356
40 35562.3734588
41 32794.5514565
42 30274.5270787
43 27980.8198753
44 25888.5092404
45 23974.1182583
46 22221.3671711
47 20614.6517335
48 19139.4835808
49 17786.0074877
50 16540.7221925
51 15394.5886672
52 14339.15372
53 13366.1433866
54 12467.9274963
55 11638.8184127
56 10871.0968088
57 10160.5688536
58 9502.28598989
59 8892.0132

## Pytorch version like numpy

In [18]:
dtype = torch.FloatTensor
N, D_in, H, D_out = 64, 1000, 100, 10
x = torch.randn(N, D_in).type(dtype)
y = torch.randn(N, D_out).type(dtype)
w1 = torch.randn(D_in, H).type(dtype)
w2 = torch.randn(H, D_out).type(dtype)
lr = 1e-6
epoch = 500
for t in range(epoch):
        #Forward pass
        h = x.mm(w1) # mm is matmul
        h_relu = h.clamp(min=0) # clamp can restrict min and max values.
        y_pred = h_relu.mm(w2)
        
        # Compute and print loss
        loss = (y_pred - y).pow(2).sum()
        print(t, loss)
        
        # Backprop
        grad_y_pred = 2.0 * (y_pred - y)
        grad_w2 = h_relu.t().mm(grad_y_pred)
        grad_h_relu = grad_y_pred.mm(w2.t())
        grad_h = grad_h_relu.clone()
        grad_h[h < 0] = 0
        grad_w1 = x.t().mm(grad_h)
        
        # Update weights using gradient descent
        w1 -= lr * grad_w1
        w2 -= lr * grad_w2

0 36040778.512674555
1 35069566.36493312
2 37918311.451746225
3 36970126.616716504
4 29011805.772612512
5 17445920.971981212
6 8737125.53978419
7 4231237.011792487
8 2306392.8251530104
9 1484785.5447464772
10 1089355.5411952839
11 861985.830115578
12 709046.3752962553
13 595102.8458470618
14 505389.9696010222
15 432605.07605131157
16 372672.1150013778
17 322718.66979431454
18 280946.26130070817
19 245739.54890472698
20 215799.94812754888
21 190223.87285178105
22 168264.02409263453
23 149343.43495539078
24 132951.59980349988
25 118701.5536364473
26 106268.35555244601
27 95395.1083058212
28 85845.74421140889
29 77430.8141505773
30 69988.57821124682
31 63395.52110686907
32 57541.94404171361
33 52336.35890817913
34 47686.07496738023
35 43520.1825810255
36 39786.98445398556
37 36433.787793740295
38 33416.55968523088
39 30693.66276819726
40 28227.130672306324
41 25989.882077297807
42 23958.5487614834
43 22111.709248300176
44 20429.602315396965
45 18895.477736635017
46 17494.481854308746
47 1

## pytorch using autograd version

In [16]:
dtype = torch.FloatTensor
N, D_in, H, D_out = 64, 1000, 100, 10
x = Variable(torch.randn(N, D_in).type(dtype), requires_grad=False)
y = Variable(torch.randn(N, D_out).type(dtype), requires_grad=False)
# requires_grad=False indicates that we do not need to compute gradients with respect to these Variables during the backward pass.

w1 = Variable(torch.randn(D_in, H).type(dtype), requires_grad=True)
w2 = Variable(torch.randn(H, D_out).type(dtype), requires_grad=True)

lr = 1e-6
epoch = 500
for t in range(500):
    # Forward pass
    # We do not need to make intermediate values because of not implementing the backward pass by hand.
    y_pred = x.mm(w1).clamp(min=0).mm(w2)
    
    loss = (y_pred - y).pow(2).sum()
    print(t, loss.data[0])
    
    # Use autograd to compute the backward pass.
    # This call will compute the gradient of loss with repect to all Variables with requires_grad=True.
    # After calling backward, you can use w1.grad and w2.grad holding the gradient each variables.
    loss.backward()
    
    # Update weights using gardient descent
    # w1.grad is Variable, but w1.grad.data is Tensor.
    w1.data -= lr * w1.grad.data
    w2.data -= lr * w2.grad.data
    
    # Don't forget to manually make the gradients zero after updating weights.
    w1.grad.data.zero_()
    w2.grad.data.zero_()

0 29255588.0
1 25987868.0
2 25885766.0
3 25321896.0
4 22210670.0
5 16820166.0
6 11029229.0
7 6598569.5
8 3830609.0
9 2300703.0
10 1483395.125
11 1039141.6875
12 781934.5
13 620411.9375
14 509867.78125
15 428538.09375
16 365437.3125
17 314660.5625
18 272786.21875
19 237700.640625
20 208008.8125
21 182686.609375
22 160947.03125
23 142203.859375
24 125966.125
25 111860.3046875
26 99562.8125
27 88794.34375
28 79362.0546875
29 71073.796875
30 63756.5234375
31 57285.2734375
32 51548.5234375
33 46452.55078125
34 41919.06640625
35 37878.64453125
36 34267.8984375
37 31041.181640625
38 28149.693359375
39 25554.2109375
40 23222.689453125
41 21124.78515625
42 19232.654296875
43 17527.03515625
44 15986.693359375
45 14593.69921875
46 13331.6787109375
47 12188.390625
48 11152.494140625
49 10211.94140625
50 9358.80859375
51 8582.7734375
52 7876.45068359375
53 7233.158203125
54 6646.552734375
55 6111.0283203125
56 5621.8515625
57 5174.44091796875
58 4765.5205078125
59 4391.15966796875
60 4048.103515625

## pytorch using nn module version

In [22]:
N, D_in, H, D_out = 64, 1000, 100, 10
x = Variable(torch.randn(N, D_in))
y = Variable(torch.randn(N, D_out), requires_grad=False)

# Use the nn package, and computes output from input using a linear function.
# nn.Sequential contains other modules.
# Each linear Module holds internal Variables for its weight and bias.
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

# The nn package contains definitions of popular loss functions
loss_fn = torch.nn.MSELoss(size_average=False)

lr = 1e-4
epoch = 500
for t in range(epoch):
    # Forwarc pass: copute predicted y
    # Module objects override the __call__ operator, so you can call them like functions.
    # When doing so you pass a Variable of input data to the Module
    # and it produces a Variabel of output data.
    y_pred = model(x)
    
    loss = loss_fn(y_pred, y)
    print(t, loss.data[0])
    
    # Make the gradients zero before running the backward pass.
    model.zero_grad()
    
    # Backward pass: compute gradient of the loss
    # with respect to all the lernable parameters in the model.
    loss.backward()
    
    # Update the weights using gradient descent.
    for param in model.parameters():
        param.data -= lr * param.grad.data

0 631.5548706054688
1 586.6476440429688
2 547.6260375976562
3 513.0361938476562
4 481.97845458984375
5 453.8518981933594
6 428.468505859375
7 405.1163024902344
8 383.5892333984375
9 363.52392578125
10 344.6094970703125
11 326.81610107421875
12 310.0614013671875
13 294.276123046875
14 279.26080322265625
15 264.94970703125
16 251.35157775878906
17 238.3685760498047
18 226.03309631347656
19 214.27761840820312
20 203.00279235839844
21 192.2000732421875
22 181.89572143554688
23 172.0153350830078
24 162.53509521484375
25 153.48745727539062
26 144.8649139404297
27 136.6582794189453
28 128.8302001953125
29 121.37068939208984
30 114.29129028320312
31 107.55888366699219
32 101.1670913696289
33 95.11398315429688
34 89.3894271850586
35 83.94060516357422
36 78.7918930053711
37 73.93345642089844
38 69.36096954345703
39 65.0478744506836
40 60.992618560791016
41 57.177001953125
42 53.58938980102539
43 50.2207145690918
44 47.05929183959961
45 44.091636657714844
46 41.3093376159668
47 38.70329666137695


## pytorch using optim version

In [26]:
N, D_in, H, D_out = 64, 1000, 100, 10
x = Variable(torch.randn(N, D_in))
y = Variable(torch.randn(N, D_out), requires_grad=False)

model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

loss_fn = torch.nn.MSELoss(size_average=False)
lr = 1e-4
epoch = 500
# Use the optim package to define an Optimizer.
# The first augument ot the Adam constructor tells the optimizer
# which Variables it should update
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
for t in range(epoch):
    # Forward pass
    y_pred = model(x)
    
    # Compute loss
    loss = loss_fn(y_pred, y)
    print(t, loss.data[0])
    
    # Before the backward pass, use the optimizer object to zero all of the gradients
    # for the variables it will update.
    optimizer.zero_grad()
    
    # Backward pass
    loss.backward()
    # Calling the step function on an Optimizer makes an update to its parameters
    optimizer.step()

0 678.932861328125
1 661.7383422851562
2 645.0687255859375
3 628.9312133789062
4 613.3612060546875
5 598.2345581054688
6 583.6022338867188
7 569.3929443359375
8 555.538330078125
9 542.1096801757812
10 529.1199340820312
11 516.532470703125
12 504.3348693847656
13 492.48321533203125
14 481.0543518066406
15 469.9525146484375
16 459.2264404296875
17 448.8131103515625
18 438.6884765625
19 428.9107971191406
20 419.4357604980469
21 410.227294921875
22 401.2049865722656
23 392.35589599609375
24 383.7286376953125
25 375.30810546875
26 367.1061096191406
27 359.1474304199219
28 351.39923095703125
29 343.8522644042969
30 336.48651123046875
31 329.28338623046875
32 322.267822265625
33 315.4294738769531
34 308.7126770019531
35 302.13720703125
36 295.6793518066406
37 289.3291931152344
38 283.0973205566406
39 276.998779296875
40 271.0439147949219
41 265.2271423339844
42 259.5158386230469
43 253.9108123779297
44 248.4178924560547
45 243.02883911132812
46 237.73248291015625
47 232.53408813476562
48 227.

## pytorch using custom nn modules version

In [29]:
class TwoLayerNet(torch.nn.Module):
    # In the constractor, which is the function to make new instance,
    # we instantiate two nn.Linear modules and assign them as member variables.
    def __init__(self, D_in, H, D_out): # This is constractor.
        super(TwoLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, D_out)
        
    # In the forward function 
    # accept a Variable of input data
    # return a Variable of output data
    # We can use Modules defined in the constructor as well as arbitrary operators on Variables.
    def forward(self, x):
        h_relu = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(h_relu)
        return y_pred
    
N, D_in, H, D_out = 64, 1000, 100, 10
x = Variable(torch.randn(N, D_in))
y = Variable(torch.randn(N, D_out), requires_grad=False)

# Constract our model by instantiating the class defined above
model = TwoLayerNet(D_in, H, D_out)
# Construct our loss function. (criterion is base.)
criterion = torch.nn.MSELoss(size_average=False)
# COnstract our optimizer .
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4)
for t in range(500):
    # Forward pass
    y_pred = model(x)

    # Compute loss
    loss = criterion(y_pred, y)
    print(t, loss.data[0])

    # Make the gradients zero
    optimizer.zero_grad()
    
    # Backward pass
    loss.backward()
    
    # Update the weights
    optimizer.step()

0 658.299072265625
1 609.6697387695312
2 567.6880493164062
3 531.1409301757812
4 498.860107421875
5 470.0181884765625
6 443.75494384765625
7 419.4953918457031
8 396.9820251464844
9 375.9394226074219
10 356.1934509277344
11 337.6008605957031
12 320.1217956542969
13 303.52935791015625
14 287.7558288574219
15 272.68292236328125
16 258.3411865234375
17 244.656494140625
18 231.6104278564453
19 219.1694793701172
20 207.2813262939453
21 195.9180908203125
22 185.0858917236328
23 174.77407836914062
24 164.97271728515625
25 155.64744567871094
26 146.79531860351562
27 138.39501953125
28 130.45457458496094
29 122.91658782958984
30 115.77137756347656
31 109.03305053710938
32 102.66154479980469
33 96.65768432617188
34 90.98259735107422
35 85.63636779785156
36 80.60208129882812
37 75.85468292236328
38 71.39073181152344
39 67.19275665283203
40 63.240596771240234
41 59.52404022216797
42 56.0333366394043
43 52.75163269042969
44 49.66996383666992
45 46.77839279174805
46 44.0676383972168
47 41.52246856689